name: "Action for Lark Notify"
description: "Action for Lark Notify with robot"
author: "kevin"
inputs:
  name:
    description: "The name of the person to greet"
    required: true
outputs:
  message:
    description: "The greeting message"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "terminal"
  color: "blue"
