name: "Action for Lark Notify"
description: "Action for Lark Notify with robot"
author: "kevin"
branding:
  icon: "terminal"
  color: "blue"

runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  header_template:
    description: "The color of Header"
    required: true
  header_content:
    description: "The content of Header"
    required: true
  message_env_tag:
    description: "The deployment env tag"
    required: true
  message_version:
    description: "The deployment version"
    required: true
  message_commit_logs:
    description: "The commit logs since last"
    required: false

outputs:
  message:
    description: "The greeting message"



