name: "Action for Lark Notify"
description: "Action for Lark Notify with robot"
author: "kevin"
branding:
  icon: "terminal"
  color: "blue"

runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  name:
    description: "The name to greet"
    required: true

outputs:
  message:
    description: "The greeting message"



