name: "Action for Lark Notify"
description: "Action for Lark Notify with robot"
author: "kevin"
branding:
  icon: "terminal"
  color: "blue"

runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  header_template:
    description: "The color of Header"
    required: true
  header_content:
    description: "The content of Header"
    required: true
  env_tag:
    description: "The deployment env tag"
    required: true

outputs:
  message:
    description: "The greeting message"



